CREATE TABLE Employees (
    employeeId NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    firstName VARCHAR(256) NOT NULL,
    lastName VARCHAR(256) NOT NULL,
    appLogin VARCHAR(256) NOT NULL,
    appPassword VARCHAR(256) NOT NULL,
    supervisor NUMBER NULL,

    CONSTRAINT Employees_pk PRIMARY KEY (employeeId),
    CONSTRAINT Employees_fk_supervisor FOREIGN KEY (supervisor) REFERENCES Employees(employeeId)
);

CREATE TABLE EmployeesPhoneNumbers (
    phoneNumberId NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    phoneNumber VARCHAR(32) NOT NULL,
    employeeId NUMBER NOT NULL,

    CONSTRAINT EmployeesPhoneNumbers_pk PRIMARY KEY (phoneNumberId),
    CONSTRAINT EmployeesPhoneNumbers_fk_employeeId FOREIGN KEY (employeeId) REFERENCES Employees(employeeId)
);

CREATE TABLE Administrators (
    employeeId NUMBER NOT NULL,
    privilegeLevel NUMBER NOT NULL,

    CONSTRAINT Administrators_pk PRIMARY KEY (employeeId),
    CONSTRAINT Administrators_fk_hh FOREIGN KEY (employeeId) REFERENCES Employees(employeeId)
);

CREATE TABLE GiftCards (
    cardNumber NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    remainingPLN NUMBER(6,2) NOT NULL,
    initialPLN NUMBER(6, 2) NOT NULL,
    issueDate DATE NOT NULL,
    expirationDate DATE NOT NULL,
    issuingEmployee NUMBER NOT NULL,

    CONSTRAINT GiftCards_pk PRIMARY KEY (cardNumber),
    CONSTRAINT GiftCards_fk_issuingEmployee FOREIGN KEY (issuingEmployee) REFERENCES Employees(employeeId)
);

CREATE TABLE Shops (
    shopId NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    shopName VARCHAR(256) NOT NULL,
    shopCity VARCHAR(256) NOT NULL,
    shopArea NUMBER(6, 2) NOT NULL,
    shopDescription VARCHAR(256) NULL,

    CONSTRAINT Shops_pk PRIMARY KEY (shopId)
);

CREATE TABLE Employments (
    employmentId NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    employedEmployeeId NUMBER NOT NULL,
    employmentDate DATE NOT NULL,
    employmentExpirationDate DATE NULL,
    employmentShopId NUMBER NOT NULL,

    CONSTRAINT Employments_pk PRIMARY KEY (employmentId),
    CONSTRAINT Employments_fk_employmentPlace FOREIGN KEY (employmentShopId) REFERENCES Shops(shopId),
    CONSTRAINT Employments_fk_employedEmployeeId FOREIGN KEY (employedEmployeeId) REFERENCES Employees(employeeId)
);

CREATE TABLE Distributors (
    distributorId NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    distributorName VARCHAR(256) NOT NULL,
    distributorEmail VARCHAR(256) NOT NULL,
    distributorPhoneNumber VARCHAR(32) NOT NULL,

    CONSTRAINT Distributors_pk PRIMARY KEY (distributorId)
);

CREATE TABLE Distributions (
    distributionId NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    shopId NUMBER NOT NULL,
    distributorId NUMBER NOT NULL,

    CONSTRAINT Distributions_pk PRIMARY KEY (distributionId),
    CONSTRAINT Distributions_fk_shopId FOREIGN KEY (shopId) REFERENCES Shops(shopId),
    CONSTRAINT Distributions_fk_distributorId FOREIGN KEY (distributorId) REFERENCES Distributors(distributorId)
);

CREATE TABLE ProductCategories (
    productCategoryId NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    categoryName VARCHAR(256) NOT NULL,

    categoryDescription VARCHAR(256) NULL,

    CONSTRAINT ProductCategories_pk PRIMARY KEY (productCategoryId)
);

CREATE TABLE Products (
    productId NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    productName VARCHAR(256) NOT NULL,
    categoryId NUMBER NOT NULL,
    netPrice NUMBER NOT NULL,
    vatPercentage NUMBER NOT NULL,

    productDescription VARCHAR(256) NULL,
    imageUrl VARCHAR(256) NULL,

    CONSTRAINT Products_pk PRIMARY KEY (productId),
    CONSTRAINT Products_fk_categoryId FOREIGN KEY (categoryId) REFERENCES ProductCategories(productCategoryId)
);

CREATE TABLE InventoryEntries (
    inventoryEntryId NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    quantity NUMBER NOT NULL,
    productId NUMBER NOT NULL,
    owningShopId NUMBER NOT NULL,

    CONSTRAINT InventoryEntries_pk PRIMARY KEY (inventoryEntryId),
    CONSTRAINT InventoryEntries_fk_productId FOREIGN KEY (productId) REFERENCES Products(productId),
    CONSTRAINT InventoryEntries_fk_owningShopId FOREIGN KEY (owningShopId) REFERENCES Shops(shopId)
);

CREATE TABLE Sales (
    saleId NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    saleDateTime TIMESTAMP NOT NULL,
    shopId NUMBER NOT NULL,

    CONSTRAINT Sales_pk PRIMARY KEY (saleId),
    CONSTRAINT Sales_fk_shopId FOREIGN KEY (shopId) REFERENCES Shops(shopId)
);

CREATE TABLE Invoices (
    invoiceNumber NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    saleId NUMBER NOT NULL,
    invoiceComment VARCHAR(256) NOT NULL,
    clientName VARCHAR(256) NOT NULL,
    clientAddress_street VARCHAR(256) NOT NULL,
    clientAddress_houseNumber VARCHAR(32) NOT NULL,
    clientAddress_postalCode VARCHAR(32) NOT NULL,
    clientAddress_city VARCHAR(32) NOT NULL,

    CONSTRAINT Invoices_pk PRIMARY KEY (invoiceNumber, saleId),
    CONSTRAINT Invoices_fk_saleId FOREIGN KEY (saleId) REFERENCES Sales(saleId)
);